2025-05-22 11:36:39,330 ERROR: Signup failed for email oussama@gmail.com: Could not determine join condition between parent/child tables on relationship Workspaces.assignments - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression. [in C:\Users\oussama\PycharmProjects\Final\Package\auth\routes\signup.py:44]
Traceback (most recent call last):
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\orm\relationships.py", line 2437, in _determine_joins
    self.primaryjoin = join_condition(
                       ~~~~~~~~~~~~~~^
        self.parent_persist_selectable,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        consider_as_foreign_keys=consider_as_foreign_keys,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\sql\util.py", line 123, in join_condition
    return Join._join_condition(
           ~~~~~~~~~~~~~~~~~~~~^
        a,
        ^^
    ...<2 lines>...
        consider_as_foreign_keys=consider_as_foreign_keys,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\sql\selectable.py", line 1443, in _join_condition
    raise exc.NoForeignKeysError(
    ...<3 lines>...
    )
sqlalchemy.exc.NoForeignKeysError: Can't find any foreign key relationships between 'workspaces' and 'assignments'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oussama\PycharmProjects\Final\Package\auth\routes\signup.py", line 21, in signup
    existing_user = db_session.query(Users).filter_by(email=form.Email.data).first()
                    ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\orm\scoping.py", line 1681, in query
    return self._proxied.query(*entities, **kwargs)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2955, in query
    return self._query_cls(entities, self, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\orm\query.py", line 276, in __init__
    self._set_entities(entities)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\orm\query.py", line 289, in _set_entities
    coercions.expect(
    ~~~~~~~~~~~~~~~~^
        roles.ColumnsClauseRole,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        post_inspect=True,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\sql\coercions.py", line 388, in expect
    insp._post_inspect
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 1257, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ~~~~~~~~~^^^^^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2724, in _post_inspect
    self._check_configure()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2401, in _check_configure
    _configure_registries({self.registry}, cascade=True)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4214, in _configure_registries
    _do_configure_registries(registries, cascade)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4255, in _do_configure_registries
    mapper._post_configure_properties()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2418, in _post_configure_properties
    prop.init()
    ~~~~~~~~~^^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\orm\interfaces.py", line 589, in init
    self.do_init()
    ~~~~~~~~~~~~^^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1658, in do_init
    self._setup_join_conditions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1898, in _setup_join_conditions
    self._join_condition = jc = JoinCondition(
                                ~~~~~~~~~~~~~^
        parent_persist_selectable=self.parent.persist_selectable,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
        can_be_synced_fn=self._columns_are_mapped,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\orm\relationships.py", line 2324, in __init__
    self._determine_joins()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\orm\relationships.py", line 2458, in _determine_joins
    raise sa_exc.NoForeignKeysError(
    ...<7 lines>...
    ) from nfe
sqlalchemy.exc.NoForeignKeysError: Could not determine join condition between parent/child tables on relationship Workspaces.assignments - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
2025-05-22 11:38:21,847 ERROR: Signup failed for email oussama@gmail.com: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[Workspaces(workspaces)]'. Original exception was: Could not determine join condition between parent/child tables on relationship Workspaces.assignments - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression. [in C:\Users\oussama\PycharmProjects\Final\Package\auth\routes\signup.py:44]
Traceback (most recent call last):
  File "C:\Users\oussama\PycharmProjects\Final\Package\auth\routes\signup.py", line 21, in signup
    existing_user = db_session.query(Users).filter_by(email=form.Email.data).first()
                    ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\orm\scoping.py", line 1681, in query
    return self._proxied.query(*entities, **kwargs)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2955, in query
    return self._query_cls(entities, self, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\orm\query.py", line 276, in __init__
    self._set_entities(entities)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\orm\query.py", line 289, in _set_entities
    coercions.expect(
    ~~~~~~~~~~~~~~~~^
        roles.ColumnsClauseRole,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        post_inspect=True,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\sql\coercions.py", line 388, in expect
    insp._post_inspect
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 1257, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ~~~~~~~~~^^^^^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2724, in _post_inspect
    self._check_configure()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2401, in _check_configure
    _configure_registries({self.registry}, cascade=True)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4214, in _configure_registries
    _do_configure_registries(registries, cascade)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oussama\PycharmProjects\Final\.venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4251, in _do_configure_registries
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[Workspaces(workspaces)]'. Original exception was: Could not determine join condition between parent/child tables on relationship Workspaces.assignments - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
2025-05-22 15:13:10,616 ERROR: Login error: 'LoginForm' object has no attribute 'Email' [in C:\Users\oussama\PycharmProjects\Final\Package\auth\routes\login.py:132]
2025-05-22 15:13:19,590 ERROR: Login error: 'LoginForm' object has no attribute 'Email' [in C:\Users\oussama\PycharmProjects\Final\Package\auth\routes\login.py:132]
